// Generated by scripts/generate_hash_registry.py; do not edit.
namespace CODNameFinder.Core;
public sealed record RegistryDomain(string Id, string Label, string? Profile, string Status, string[] Kinds, string Source);
public static class GeneratedRegistry
{
    public const string Sha256 = "29b10a75a39a8e751d12ecc39ca8a4a08095315b226e61e88247398f8f9efed6";
    public static readonly string[] ProfileIds = ["iw-resource63","fnv1a63","fnv1a64","fnv1a64-raw","fnv1a32","bo3-bo4-early-script32","bo4-bocw-script32","mwii-mwiii-script64","mwii-mwiii-script63","iw-dvar64","bo6-script64","bo6-sp-script64","bo6-omnvar64","prime32","djb2-xor32","kvp64","sab-sdbm32","sab-fnv1a64","fnv1a60","fnv1a63-no-fold"];
    public static readonly IReadOnlyDictionary<string, RegistryDomain[]> Domains = new Dictionary<string, RegistryDomain[]>(StringComparer.Ordinal)
    {
        ["BO4"] = [
            new("asset","资产名称","fnv1a63","evidence",["xmodel","xanim","image","material","sndasset","soundbank","soundbanktransient","animpkg","rawfile","scriptfile","scriptbundle","stringtable","localize","weapon","attachment","structuredtable","keyvaluepairs"],"docs/hash-algorithm-coverage.md"),
            new("script","脚本字段","bo4-bocw-script32","evidence",["scriptfield","script","scriptfunction"],"docs/hash-algorithm-coverage.md"),
            new("script-early","早期脚本 VM31","bo3-bo4-early-script32","evidence",["scriptfield","script","scriptfunction"],"docs/hash-algorithm-coverage.md"),
            new("structuredtable","结构表键","prime32","evidence",["structuredtable"],"docs/hash-algorithm-coverage.md"),
            new("keyvaluepairs","KVP","kvp64","evidence",["keyvaluepairs"],"docs/hash-algorithm-coverage.md"),
            new("sound-nofold","声音路径（保留反斜杠）","fnv1a63-no-fold","candidate",["sndasset"],"hash-slinging-slasher/docs/HASHES.md and BO4 sound no-fold rows"),
        ],
        ["MW2019"] = [
            new("asset","资源名称索引","iw-resource63","evidence",["xmodel","xanim","image","material","sndasset","soundbank","soundbanktransient","animpkg","rawfile","scriptfile","scriptbundle","stringtable","localize","weapon","attachment","structuredtable","keyvaluepairs"],"docs/hash-algorithm-coverage.md"),
            new("tag","类型名称","fnv1a32","evidence",["tag","assettype"],"docs/hash-algorithm-coverage.md"),
        ],
        ["BOCW"] = [
            new("asset","资产名称","fnv1a63","evidence",["xmodel","xanim","image","material","sndasset","soundbank","soundbanktransient","animpkg","rawfile","scriptfile","scriptbundle","stringtable","localize","weapon","attachment","structuredtable","keyvaluepairs"],"docs/hash-algorithm-coverage.md"),
            new("script","脚本字段","bo4-bocw-script32","evidence",["scriptfield","script","scriptfunction"],"docs/hash-algorithm-coverage.md"),
            new("keyvaluepairs","KVP","kvp64","evidence",["keyvaluepairs"],"docs/hash-algorithm-coverage.md"),
            new("bone","骨骼 / Notify 字符串（60位）","fnv1a60","evidence",["bone","notify","string"],"hash-slinging-slasher/docs/HASHES.md; fnv1a_strings"),
        ],
        ["Vanguard"] = [
            new("asset","资源名称索引","iw-resource63","evidence",["xmodel","xanim","image","material","sndasset","soundbank","soundbanktransient","animpkg","rawfile","scriptfile","scriptbundle","stringtable","localize","weapon","attachment","structuredtable","keyvaluepairs"],"docs/hash-algorithm-coverage.md"),
            new("sab","SAB V17 声音名称","sab-fnv1a64","evidence",["sab"],"docs/hash-algorithm-coverage.md"),
        ],
        ["MWII"] = [
            new("asset","资产名称","iw-resource63","evidence",["xmodel","xanim","image","material","sndasset","soundbank","soundbanktransient","animpkg","rawfile","scriptfile","scriptbundle","stringtable","localize","weapon","attachment","structuredtable","keyvaluepairs"],"docs/hash-algorithm-coverage.md"),
            new("script","脚本完整键","mwii-mwiii-script64","evidence",["scriptfield","script","scriptfunction"],"docs/hash-algorithm-coverage.md"),
            new("script-stored63","脚本存储63位","mwii-mwiii-script63","evidence",["scriptfield","script","scriptfunction"],"docs/hash-algorithm-coverage.md"),
            new("dvar","Dvar","iw-dvar64","evidence",["dvar"],"docs/hash-algorithm-coverage.md"),
            new("tag","Tag / 类型名称","fnv1a32","evidence",["tag","assettype"],"docs/hash-algorithm-coverage.md"),
            new("soundbankalias","声音银行别名（Treyarch 满64位）","fnv1a64","evidence",["soundbankalias","alias"],"hash-slinging-slasher/docs/HASHES.md; aliases_v2"),
            new("bone","骨骼名称","fnv1a32","evidence",["bone"],"hash-slinging-slasher/docs/HASHES.md; bones / bones_v2"),
        ],
        ["MWIII"] = [
            new("asset","资产名称","iw-resource63","evidence",["xmodel","xanim","image","material","sndasset","soundbank","soundbanktransient","animpkg","rawfile","scriptfile","scriptbundle","stringtable","localize","weapon","attachment","structuredtable","keyvaluepairs"],"docs/hash-algorithm-coverage.md"),
            new("script","脚本完整键","mwii-mwiii-script64","evidence",["scriptfield","script","scriptfunction"],"docs/hash-algorithm-coverage.md"),
            new("script-stored63","脚本存储63位","mwii-mwiii-script63","evidence",["scriptfield","script","scriptfunction"],"docs/hash-algorithm-coverage.md"),
            new("dvar","Dvar","iw-dvar64","evidence",["dvar"],"docs/hash-algorithm-coverage.md"),
            new("soundbankalias","声音银行别名（Treyarch 满64位）","fnv1a64","evidence",["soundbankalias","alias"],"hash-slinging-slasher/docs/HASHES.md; aliases_v2"),
            new("bone","骨骼名称","fnv1a32","evidence",["bone"],"hash-slinging-slasher/docs/HASHES.md; bones / bones_v2"),
        ],
        ["BO6"] = [
            new("asset","资产名称","iw-resource63","evidence",["xmodel","xanim","image","material","sndasset","soundbank","soundbanktransient","animpkg","rawfile","scriptfile","scriptbundle","stringtable","localize","weapon","attachment","structuredtable","keyvaluepairs"],"docs/hash-algorithm-coverage.md"),
            new("script","脚本字段","bo6-script64","evidence",["scriptfield","script","scriptfunction"],"docs/hash-algorithm-coverage.md"),
            new("script-sp","战役 VM0b 脚本","bo6-sp-script64","evidence",["scriptfield","script","scriptfunction"],"docs/hash-algorithm-coverage.md"),
            new("dvar","Dvar","iw-dvar64","evidence",["dvar"],"docs/hash-algorithm-coverage.md"),
            new("omnvar","Omnvar","bo6-omnvar64","evidence",["omnvar"],"docs/hash-algorithm-coverage.md"),
            new("hashliteral","# 值","fnv1a64","evidence",["hashliteral"],"docs/hash-algorithm-coverage.md"),
            new("tag","Tag","fnv1a32","evidence",["tag","assettype"],"docs/hash-algorithm-coverage.md"),
            new("soundbankalias","声音银行别名（Treyarch 满64位）","fnv1a64","evidence",["soundbankalias","alias"],"hash-slinging-slasher/docs/HASHES.md; aliases_v2"),
            new("bone-v2","骨骼名称（bones_v2 满64位）","fnv1a64","evidence",["bone"],"hash-slinging-slasher/docs/HASHES.md; bones / bones_v2"),
        ],
        ["BO7"] = [
            new("asset","资产名称","iw-resource63","evidence",["xmodel","xanim","image","material","sndasset","soundbank","soundbanktransient","animpkg","rawfile","scriptfile","scriptbundle","stringtable","localize","weapon","attachment","structuredtable","keyvaluepairs"],"docs/hash-algorithm-coverage.md"),
            new("script","脚本字段","bo6-script64","evidence",["scriptfield","script","scriptfunction"],"docs/hash-algorithm-coverage.md"),
            new("dvar","Dvar","iw-dvar64","evidence",["dvar"],"docs/hash-algorithm-coverage.md"),
            new("omnvar","Omnvar","bo6-omnvar64","evidence",["omnvar"],"docs/hash-algorithm-coverage.md"),
            new("hashliteral","# 值","fnv1a64","evidence",["hashliteral"],"docs/hash-algorithm-coverage.md"),
            new("tag","Tag","fnv1a32","evidence",["tag","assettype"],"docs/hash-algorithm-coverage.md"),
            new("soundbankalias","声音银行别名（Treyarch 满64位）","fnv1a64","evidence",["soundbankalias","alias"],"hash-slinging-slasher/docs/HASHES.md; aliases_v2"),
            new("bone-v2","骨骼名称（bones_v2 满64位）","fnv1a64","evidence",["bone"],"hash-slinging-slasher/docs/HASHES.md; bones / bones_v2"),
        ],
        ["声音容器 / 手动核验"] = [
            new("sab-sdbm32","SAB 旧版名称","sab-sdbm32","evidence",["sab"],"docs/hash-algorithm-coverage.md"),
            new("sab-fnv1a64","SAB V17 名称","sab-fnv1a64","evidence",["sab"],"docs/hash-algorithm-coverage.md"),
        ],
        ["COD2026"] = [
            new("asset","资产名称 / 动画包 / 声音库 / 声音文件","iw-resource63","evidence",["xmodel","xanim","image","material","sndasset","soundbank","soundbanktransient","animpkg","rawfile","scriptfile","scriptbundle","stringtable","localize","weapon","attachment","structuredtable","keyvaluepairs"],"cod-name-db rex table audit 2026-10-05; docs/hash-algorithm-coverage.md"),
            new("soundbankalias","声音银行别名（Treyarch 满64位）","fnv1a64","evidence",["soundbankalias","alias"],"cod-name-db rex table audit 2026-10-05; docs/hash-algorithm-coverage.md"),
            new("script","脚本字段",null,"unknown",["scriptfield","script"],"No build-specific hash/name vectors; intentionally gated"),
            new("scriptfunction","脚本函数",null,"unknown",["scriptfunction"],"No build-specific hash/name vectors; intentionally gated"),
            new("dvar","Dvar",null,"unknown",["dvar"],"No build-specific hash/name vectors; intentionally gated"),
            new("omnvar","Omnvar",null,"unknown",["omnvar"],"No build-specific hash/name vectors; intentionally gated"),
            new("bone-v2","骨骼名称（尚未证实）",null,"unknown",["bone"],"No COD2026-specific bones_v2 known hash/name vectors; no default inferred"),
        ],
    };
}
