"""Generate runtime metadata from the sole editable registry (no network access)."""
from __future__ import annotations
import argparse
import hashlib
import json
from pathlib import Path
import pprint

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'docs/hash-registry.json'


def validate(data):
    if data.get('schema_version') != 2:
        raise ValueError('Unsupported registry schema')
    ids = [p['id'] for p in data['profiles']]
    if len(ids) != len(set(ids)):
        raise ValueError('Duplicate profile id')
    algorithms = data['algorithms']
    native_ids = [v['native_id'] for v in algorithms.values()]
    if len(native_ids) != len(set(native_ids)):
        raise ValueError('Duplicate native algorithm id')
    for name, entry in algorithms.items():
        if entry['native_id'] != entry['opencl_id']:
            raise ValueError('Native/OpenCL dispatch drift: ' + name)
    for p in data['profiles']:
        if p['algorithm'] not in algorithms or p['status'] not in ('evidence', 'candidate', 'unknown'):
            raise ValueError('Invalid profile metadata: ' + p['id'])
        if not 0 <= p['seed'] < 2**64 or not 0 < p['mask'] < 2**64 or not 0 < p['prime'] < 2**64:
            raise ValueError('Invalid profile parameters: ' + p['id'])
    for game, domains in data['domains'].items():
        for domain in domains:
            if domain['status'] == 'unknown':
                if domain['profile'] is not None:
                    raise ValueError('Unknown domain cannot have a default profile: ' + game)
            elif domain['profile'] not in ids:
                raise ValueError('Invalid domain profile: ' + game)
    for table in data['tables']:
        if table['profile'] is not None and table['profile'] not in ids:
            raise ValueError('Invalid table profile')


def outputs():
    raw = SOURCE.read_bytes()
    data = json.loads(raw)
    validate(data)
    digest = hashlib.sha256(raw).hexdigest()
    header = '# Generated by scripts/generate_hash_registry.py; do not edit.\n'
    values = {k: data[k] for k in ('algorithms', 'profiles', 'domains', 'tables')}
    py = header + f'REGISTRY_SHA256 = {digest!r}\n'
    for key, value in values.items():
        py += key.upper() + ' = ' + pprint.pformat(value, width=110, sort_dicts=False) + '\n'
    py += 'GAME_DOMAINS = {g: {d["label"]: d["profile"] for d in ds if d["status"] == "evidence"} for g, ds in DOMAINS.items()}\n'
    rust = '// Generated by scripts/generate_hash_registry.py; do not edit.\n'
    rust += f'pub const REGISTRY_SHA256: &str = "{digest}";\n'
    for name, entry in data['algorithms'].items():
        rust += f'pub const ALG_{name.upper().replace("-", "_")}: u32 = {entry["native_id"]};\n'
    defines = '\n'.join(f'#define ALG_{name.upper().replace("-", "_")} {entry["opencl_id"]}'
                        for name, entry in data['algorithms'].items()) + '\n'
    py += f'OPENCL_DEFINES = {defines!r}\n'
    cs = '// Generated by scripts/generate_hash_registry.py; do not edit.\nnamespace CODNameFinder.Core;\n'
    cs += 'public sealed record RegistryDomain(string Id, string Label, string? Profile, string Status, string[] Kinds, string Source);\n'
    cs += 'public static class GeneratedRegistry\n{\n'
    cs += f'    public const string Sha256 = "{digest}";\n'
    cs += '    public static readonly string[] ProfileIds = [' + ','.join(json.dumps(p['id']) for p in data['profiles']) + '];\n'
    cs += '    public static readonly IReadOnlyDictionary<string, RegistryDomain[]> Domains = new Dictionary<string, RegistryDomain[]>(StringComparer.Ordinal)\n    {\n'
    for game, domains in data['domains'].items():
        cs += '        [' + json.dumps(game, ensure_ascii=False) + '] = [\n'
        for d in domains:
            args = [json.dumps(d['id']), json.dumps(d['label'], ensure_ascii=False), json.dumps(d['profile']), json.dumps(d['status']),
                    '[' + ','.join(json.dumps(k) for k in d['kinds']) + ']', json.dumps(d['source'], ensure_ascii=False)]
            cs += '            new(' + ','.join(args) + '),\n'
        cs += '        ],\n'
    cs += '    };\n}\n'
    return {ROOT / 'finder/generated_registry.py': py,
            ROOT / 'native/src/registry_generated.rs': rust,
            ROOT / 'dotnet/CODNameFinder.Core/GeneratedRegistry.cs': cs}


def generate(check=False):
    stale = []
    for path, content in outputs().items():
        if check:
            if not path.is_file() or path.read_text(encoding='utf-8') != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding='utf-8', newline='\n')
    if stale:
        raise ValueError('Registry generation is stale: ' + ', '.join(stale))


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    generate(parser.parse_args().check)
