// Generated by scripts/generate_hash_registry.py; do not edit.
pub const REGISTRY_SHA256: &str = "29b10a75a39a8e751d12ecc39ca8a4a08095315b226e61e88247398f8f9efed6";
pub const ALG_FNV: u32 = 0;
pub const ALG_BO4_SCRIPT: u32 = 1;
pub const ALG_T7_SCRIPT: u32 = 2;
pub const ALG_SECURE: u32 = 3;
pub const ALG_SUFFIX: u32 = 4;
pub const ALG_PRIME32: u32 = 5;
pub const ALG_DJB2XOR: u32 = 6;
pub const ALG_KVP: u32 = 7;
